# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.TextField()),
                ('logo', models.ImageField(upload_to=b'')),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
