# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20170527_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='adress',
            new_name='address',
        ),
    ]
