# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20170527_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Shopping')),
            ],
        ),
    ]
